name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'package/lib/**'
      - 'tests/**'
      - '.github/workflows/tests.yaml'
  pull_request:
  workflow_dispatch:

env:
  CI: true
jobs:
  Test:
    if: github.repository == 'vnphanquang/postcss-color-scheme' # prevents this action from running on forks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts --no-frozen-lockfile

      - name: Lint
        run: 'pnpm lint'

      - name: Run Integrations Tests
        run: 'pnpm ci:test:integrations'

      - name: Run Unit Tests
        run: 'pnpm ci:test:units'

      - name: Upload Test Results
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage/junit.xml
          flags: unittests, ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests, ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
